const fs = require('fs');
const path = require('path');
const { parse } = require('csv-parse/sync');

const root = path.resolve(__dirname, '..');
const dataDir = path.join(root, 'data');
const outDir = path.join(root, 'prolog', 'generated');
fs.mkdirSync(outDir, { recursive: true });

const readCsv = name => parse(fs.readFileSync(path.join(dataDir, name), 'utf8'), {
  columns: true,
  skip_empty_lines: true
});

const master = readCsv('myanmar_mammals_master.csv');
const traits = readCsv('mammal_traits.csv');
const traitSchema = JSON.parse(fs.readFileSync(path.join(dataDir, 'trait_schema.json'), 'utf8'));
const questionSchema = JSON.parse(fs.readFileSync(path.join(dataDir, 'question_schema.json'), 'utf8'));
const questionConstraintsPath = path.join(dataDir, 'question_constraints.json');
const questionConstraints = fs.existsSync(questionConstraintsPath)
  ? JSON.parse(fs.readFileSync(questionConstraintsPath, 'utf8'))
  : {};

const traitDefs = traitSchema.traits.filter(t => t.questionable && t.data_type === 'enum');
const traitIds = traitDefs.map(t => t.id);
const traitById = new Map(traitDefs.map(t => [t.id, t]));
const masterByKey = new Map(master.map(row => [row.species_key, row]));

const atomRe = /^[a-z][a-z0-9_]*$/;
function atom(value) {
  const s = String(value || '').trim();
  if (atomRe.test(s)) return s;
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function qstring(value) {
  return `"${String(value || '').replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function isActive(row) {
  const masterRow = masterByKey.get(row.species_key);
  if (!masterRow) throw new Error(`Trait row missing from master dataset: ${row.species_key}`);
  if (String(masterRow.identification_active || '').trim().toLowerCase() === 'false') return false;
  return traitIds.some(id => String(row[id] || '').trim());
}

function validateValue(speciesKey, traitId, raw) {
  const value = String(raw || '').trim();
  if (!value) return null;
  const def = traitById.get(traitId);
  if (!def.allowed_values.includes(value)) {
    throw new Error(`${speciesKey}/${traitId}: invalid enum value '${value}'`);
  }
  return value;
}

const activeRows = traits.filter(isActive).sort((a, b) => a.species_key.localeCompare(b.species_key));
let traitFactCount = 0;
const lines = [
  '/* Generated by scripts/generatePrologKnowledge.js. Do not edit by hand. */',
  ':- module(mammal_traits, [',
  '    animal/1, scientific_name/2, common_name/2, animal_order/2, animal_family/2,',
  '    trait/3, trait_weight/2, trait_allowed/2, trait_group/2, trait_applicability/2,',
  '    question/3, question_pool/2, specialized_pool/2,',
  '    domain_gate/2, domain_gate_order/2, domain_gate_body_form/2,',
  '    question_domain_gate/2, question_penalty/5, question_block_if/4, question_bonus/5,',
  '    generated_candidate_count/1, generated_trait_fact_count/1',
  ']).',
  ':- discontiguous animal/1.',
  ':- discontiguous scientific_name/2.',
  ':- discontiguous common_name/2.',
  ':- discontiguous animal_order/2.',
  ':- discontiguous animal_family/2.',
  ':- discontiguous trait/3.',
  ':- discontiguous trait_weight/2.',
  ':- discontiguous trait_allowed/2.',
  ':- discontiguous trait_group/2.',
  ':- discontiguous trait_applicability/2.',
  ':- discontiguous question/3.',
  ':- discontiguous question_pool/2.',
  ':- discontiguous specialized_pool/2.',
  ':- discontiguous domain_gate/2.',
  ':- discontiguous domain_gate_order/2.',
  ':- discontiguous domain_gate_body_form/2.',
  ':- discontiguous question_domain_gate/2.',
  ':- discontiguous question_penalty/5.',
  ':- discontiguous question_block_if/4.',
  ':- discontiguous question_bonus/5.',
  ''
];

for (const row of activeRows) {
  const masterRow = masterByKey.get(row.species_key);
  lines.push(`animal(${atom(row.species_key)}).`);
  lines.push(`scientific_name(${atom(row.species_key)}, ${qstring(row.scientific_name)}).`);
  lines.push(`common_name(${atom(row.species_key)}, ${qstring(masterRow.common_name || row.scientific_name)}).`);
  lines.push(`animal_order(${atom(row.species_key)}, ${atom(masterRow.order)}).`);
  lines.push(`animal_family(${atom(row.species_key)}, ${atom(masterRow.family)}).`);
  for (const traitId of traitIds) {
    const value = validateValue(row.species_key, traitId, row[traitId]);
    if (!value) continue;
    lines.push(`trait(${atom(row.species_key)}, ${atom(traitId)}, ${atom(value)}).`);
    traitFactCount++;
  }
  lines.push('');
}

for (const def of traitDefs) {
  lines.push(`trait_weight(${atom(def.id)}, ${Number(def.evidence_weight || 1)}).`);
  lines.push(`trait_allowed(${atom(def.id)}, [${def.allowed_values.map(atom).join(', ')}]).`);
  lines.push(`trait_group(${atom(def.id)}, ${atom(def.group)}).`);
  lines.push(`trait_applicability(${atom(def.id)}, ${atom(def.applicability)}).`);
}
lines.push('');

for (const [id, q] of Object.entries(questionSchema.questions)) {
  if (!traitById.has(id)) continue;
  const def = traitById.get(id);
  const options = def.allowed_values.map(value => {
    const label = (q.option_labels && q.option_labels[value]) || value.replace(/_/g, ' ');
    return `option(${atom(value)}, ${qstring(label)})`;
  });
  if (q.always_offer_unknown !== false) options.push(`option(unknown, ${qstring('Not sure')})`);
  lines.push(`question(${atom(id)}, ${qstring(q.prompt)}, [${options.join(', ')}]).`);
}
lines.push('');

for (const id of questionSchema.opening_pool || []) if (traitById.has(id)) lines.push(`question_pool(opening, ${atom(id)}).`);
for (const id of questionSchema.general_followup_pool || []) if (traitById.has(id)) lines.push(`question_pool(general_followup, ${atom(id)}).`);
for (const [pool, ids] of Object.entries(questionSchema.specialized_pools || {})) {
  for (const id of ids) if (traitById.has(id)) lines.push(`specialized_pool(${atom(pool)}, ${atom(id)}).`);
}
lines.push('');

for (const [gate, config] of Object.entries(questionConstraints.domain_gates || {})) {
  lines.push(`domain_gate(${atom(gate)}, ${qstring(gate.replace(/_/g, ' '))}).`);
  for (const order of config.orders || []) lines.push(`domain_gate_order(${atom(gate)}, ${atom(order)}).`);
  for (const value of config.body_form_values || []) lines.push(`domain_gate_body_form(${atom(gate)}, ${atom(value)}).`);
  for (const trait of config.traits || []) {
    if (traitById.has(trait)) lines.push(`question_domain_gate(${atom(trait)}, ${atom(gate)}).`);
  }
}
for (const [trait, entries] of Object.entries(questionConstraints.penalties || {})) {
  if (!traitById.has(trait)) continue;
  for (const entry of entries || []) {
    for (const value of entry.values || []) {
      lines.push(
        `question_penalty(${atom(trait)}, ${atom(entry.attribute)}, ${atom(value)}, ${Number(entry.penalty || 0)}, ${qstring(entry.reason || '')}).`
      );
    }
  }
}
for (const [trait, config] of Object.entries(questionConstraints.prerequisites || {})) {
  if (!traitById.has(trait)) continue;
  for (const entry of config.blocked_by || []) {
    for (const value of entry.values || []) {
      lines.push(`question_block_if(${atom(trait)}, ${atom(entry.attribute)}, ${atom(value)}, ${qstring(entry.reason || '')}).`);
    }
  }
  for (const entry of config.boosted_by || []) {
    for (const value of entry.values || []) {
      lines.push(
        `question_bonus(${atom(trait)}, ${atom(entry.attribute)}, ${atom(value)}, ${Number(entry.bonus || 0)}, ${qstring(entry.reason || '')}).`
      );
    }
  }
}
lines.push('');
lines.push(`generated_candidate_count(${activeRows.length}).`);
lines.push(`generated_trait_fact_count(${traitFactCount}).`);

fs.writeFileSync(path.join(outDir, 'mammal_traits.pl'), `${lines.join('\n')}\n`);
console.log(`Generated prolog/generated/mammal_traits.pl`);
console.log(`Active Prolog candidates: ${activeRows.length}`);
console.log(`Trait facts: ${traitFactCount}`);
